version: "3.9"

services:
  core:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    container_name: v2ray
    ports:
      - "8888:8888"
    volumes:
      - ./config/config.json:/etc/v2ray/config.json
      - ./log:/var/log/v2ray
      - /home/ubuntu/nginx:/home/ubuntu/nginx
